### ISSUE TITLE
Plotting in the ace.py:227 accepts only int while the output len(myace.ace.x)/2  is float

### ISSUE THREAD

**Issue by snowlover173** [partofthething/ace#16]
I ran the sample wang example and ran to the issue because it does a 
num_cols = len(ace_model.x) / 2 + 1  equal to 3.5.
that cause the value of num_cols be 3.5. I removed one of arrays in the x. Now I have 4 x samples. But again plotting threw the error because it is considering it as float . 

ValueError: Number of rows must be a positive integer, not 3.0

PS.: "Successfully installed ace-0.3.2"

**Comment by partofthething** [comment]
Ooops yup that's a good point. That used to be integer division but as python evolved it's now float division. I'll fix. Thanks for report.

**Comment by partofthething** [comment]
Should be all fixed in new release v0.3.3
