### ISSUE TITLE
ACE algorithm is too slow

### ISSUE THREAD

**Issue by partofthething** [partofthething/ace#2]
The initial implementation of ACE that's active does not make use of the update capability of the fixed-span smoother. This makes ACE really slow, as confirmed by this profiling result (made with [gprof2dot](https://code.google.com/p/jrfonseca/wiki/Gprof2Dot)):

![ace_profiled](https://cloud.githubusercontent.com/assets/5360219/4364852/ac65b58e-42a4-11e4-99d6-0245f9a2ef6d.png)

Next step is to just modify the fixed-span smoother to update intelligently. Should be easy.

**Comment by Stanpol** [comment]
Can it be parallelized to utilize multiple cores?

**Comment by partofthething** [comment]
@Stanpol almost definitely. I'd have profile it again and double-check the algorithm to be sure but I think a lot of the smoothing work could be done in parallel.

**Comment by paulperry** [comment]
How about use of a GPU? On top of RAPIDS, JAX, or some other library?

**Comment by partofthething** [comment]
GPU may help. But if we want really fast ACE with this library it might be more straightforward to try to push more of the work to vectorized numpy stuff and/or cython the key parts. 

Frankly, the original [1985 FORTRAN version ](http://lib.stat.cmu.edu/general/ace)of ACE is extraordinarily fast. This implementation was originally intended as a learning tool. For large datasets it may make more sense to just wrap OG ACE with f2py and use that from python. If anyone's interested in that I've done it before and could try to turn it into an option of this lib or a new lib.

**Comment by paulperry** [comment]
The original FORTRAN code doesn't help to transition off the CPU, while writing to Numpy could help support both CPU and GPU/TPU's with very little or no change: [JAX](https://github.com/google/jax) in a numpy compatible API with jit compilation, and [CuPy](https://github.com/cupy/cupy) is a "NumPy-like API accelerated with CUDA".  There is also [CuDF](https://github.com/rapidsai/cudf), a  pandas-like API, that may have some of the functionality you need.  I have no idea what it would take to implement, but I think an accelerated ACE would be more broadly applicable.
