### ISSUE TITLE
The validation problems have invalid imports

### ISSUE THREAD

**Issue by SimplyKnownAsG** [partofthething/ace#5]
The "validation" problems have invalid imports.

Specifically, line 11 of `smoother_friedman82.py` should be:

```python
from .. import smoother
```
This is consisstent with both standards for [Python 2.7](https://docs.python.org/2.7/reference/simple_stmts.html#the-import-statement) and [Python 3.5](
https://docs.python.org/3.5/reference/simple_stmts.html#the-import-statement)

**Comment by partofthething** [comment]
Good fix. Thanks.
