### ISSUE TITLE
validate_smoothers.py relies on "mace" a package that doesn't appear to exist

### ISSUE THREAD

**Issue by SimplyKnownAsG** [partofthething/ace#7]
I'm not sure if this is an error on my part or from something else, but I cannot find the package "mace" on PyPI.

This script doesn't appear to run ever though, so I'm not sure it is too important.

**Comment by partofthething** [comment]
It's the F2PY'd version of the original ACE FORTRAN code from Breiman. I didn't include it in this repo but included the test code in case anyone else wanted to do direct comparisons. I should maybe make that more clear in the docstrings and maybe in a `ImportError` so it's clear.

**Comment by partofthething** [comment]
I added the `ImportError`. Hope that helps people.
